apiVersion: v1
kind: Service
metadata:
  name: net-attach-def-admission-controller-service
  labels:
    service: net-attach-def-admission-controller-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 443
  - name: metrics
    port: 9091
    targetPort: https
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: net-attach-def-admission-controller
